services:
  mysql_container:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "${MYSQL_PORT}:3306" # <--- Left side dynamic
    volumes:
      - mysql_data:/var/lib/mysql

  backend_container:
    build: ./backend
    restart: always
    ports:
      - "${BACKEND_PORT}:5000" # <--- Left side dynamic
    depends_on:
      - mysql_container
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}

  frontend_container:
    build: ./frontend
    restart: always
    ports:
      - "${FRONTEND_PORT}:80" # <--- Left side dynamic
    depends_on:
      - backend_container
